### ISSUE TITLE
Disable gitweb

### ISSUE THREAD

**Issue by tboerger** [crowbar/barclamp-crowbar#1323]
I think we should disable gitweb on the admin server, currently if you access the admin server with the subfolder /git you are getting on the gitweb index page.

**Comment by vuntz** [comment]
Huh? I guess you're using the git barclamp which is being dropped?

**Comment by tboerger** [comment]
Hum, yeah this is still on the machine. Does this file come in with package git?

**Comment by vuntz** [comment]
I don't know what else would install the gitweb index page :-)

**Comment by tboerger** [comment]
So let's close this. The git barclamp is not used anymore by the current version.
